# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 12:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('passenger_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=250)),
                ('lname', models.CharField(max_length=250)),
                ('billing_address', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('reservation_date', models.DateField(default=datetime.datetime.today)),
                ('paying_passenger_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turk.Passenger')),
            ],
        ),
        migrations.CreateModel(
            name='Seats_Free',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_free_date', models.DateField(default=datetime.datetime.today)),
                ('free_seat', models.IntegerField(default=448)),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('segment_id', models.AutoField(primary_key=True, serialize=False)),
                ('seg_fare', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.AutoField(primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('stop_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_in', models.TimeField(default=datetime.datetime.now)),
                ('time_out', models.TimeField(default=datetime.datetime.now)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turk.Station')),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('train_id', models.AutoField(primary_key=True, serialize=False)),
                ('train_direction', models.BooleanField(default=0)),
                ('train_days', models.BooleanField(default=1)),
                ('train_end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_end', to='turk.Station')),
                ('train_start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_start', to='turk.Station')),
            ],
        ),
        migrations.AddField(
            model_name='stop',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turk.Train'),
        ),
        migrations.AddField(
            model_name='segment',
            name='segment_north',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seg_n', to='turk.Station'),
        ),
        migrations.AddField(
            model_name='segment',
            name='segment_south',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seg_s', to='turk.Station'),
        ),
        migrations.AddField(
            model_name='seats_free',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turk.Segment'),
        ),
        migrations.AddField(
            model_name='seats_free',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turk.Train'),
        ),
    ]
