# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 18:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('fare', models.FloatField(default=0)),
                ('trip_date', models.DateField(default=datetime.datetime.today)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turk.Reservation')),
                ('trip_end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_end', to='turk.Station')),
                ('trip_start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_start', to='turk.Station')),
            ],
        ),
    ]
